name: html wep page cicd
on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on : ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6


      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: build docker image
        run: |
          docker build \
            -t ${{ vars.DOCKERHUB_USERNAME }}/web_page:latest .

      - name: docker images
        run: |
          docker images

      - name: push docker image
        run: |
          docker push ${{ vars.DOCKERHUB_USERNAME }}/web_page:latest
      - name: deploy to ec2 instance
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ vars.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script:
            echo " start deployment "
            docker pull ${{ vars.DOCKER_USERNAME }}/web_page:latest
            docker stop web_page || true
            docker rm web_page || true

            docker run -d \
              --name portfoli web_page\
              --network web_network \
              -p 8080:80 \
              -v web_data\
              ${{ vars.DOCKER_USERNAME }}/web_page:latest 

            docker ps
            
            echo "deployment completed"

          
        
