name: html wep page cicd
on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on : ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6


      - name: login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: build docker image
        run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/web_page:latest .
        
